[package]
name = "rt-one-weekend"
version = "0.1.0"
authors = ["jakmeier"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.20"
ncollide3d = "0.22"
png = "0.16.7"
rand = "0.7.3"