spin_manifest_version = "1"
authors = ["Jakob Meier <mail@jakobmeier.ch>"]
description = "Simple HTTP component for the Spin framework. Provides RT-rendering workers."
name = "spin-component"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-component"
source = "res/spin_component.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release; wasm-opt -O2 --fast-math $CARGO_TARGET_DIR/wasm32-wasi/release/spin_component.wasm -o res/spin_component.wasm"
watch = ["src/**/*.rs", "Cargo.toml"]
